services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "82:82"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx.conf to container
    restart: always
    depends_on:
      - zitadel
      - backend
        

  db:
    image: postgres:16-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres", "||", "exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  zitadel:
    user: "${UID:-1000}"
    restart: always
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    ports:
      - '8080:8080'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: "false"
      ZITADEL_EXTERNALDOMAIN: "zitadel"
      ZITADEL_EXTERNALPORT: "82"
      ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH: /machinekey/zitadel-admin-sa.json
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME: zitadel-admin-sa
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME: Admin
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE: 1
    volumes:
      - ./machinekey:/machinekey
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./raggenie.db:/app/raggenie.db
      - ./assets:/app/assets
      - ./chromadb:/app/chromadb
      - ./machinekey:/app/machinekey
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ZITADEL_TOKEN_URL=http://zitadel:8080/oauth/v2/token
      - ZITADEL_DOMAIN=http://zitadel:8080 
      - APP_SERVER=http://localhost:8001
      - CLIENT_PRIVATE_KEY_FILE_PATH=machinekey/zitadel-admin-sa.json
    command: 'python3 main.py --config ./config.yaml llm'
    depends_on:
      - zitadel
