version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "source /opt/venv/bin/activate && python main.py --config ./config.yaml llm"

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ui:/app
    depends_on:
      - backend